### ISSUE TITLE
build failed - No such file or directory (os error 2)

### ISSUE THREAD

**Issue by avp90** [RustRPM/cargo-rpm#33]
If i run `cargo rpm build -v` on `macOS Mojave` it fails with the following output:
```
    Running cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
    Creating release archive: BE_ApiGateway2-0.1.0.tar.gz
error: I/O error: No such file or directory (os error 2)
```

**Comment by tarcieri** [comment]
Not the world's greatest error message unfortunately. If we can figure out where this is happening perhaps we can improve it.

Can you try running it under `strace` and seeing which file/directory doesn't exist? We can trace it down from there.

**Comment by avp90** [comment]
Hi @tarcieri,  
here is the output of the `dtruss`  
(`strace` equivalent for macOS - command `sudo dtruss -f -t open cargo rpm build -v`)  
  
```
    PID/THRD  SYSCALL(args)          = return
     Running cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
    Creating release archive: BE_ApiGateway2-0.1.0.tar.gz
error: I/O error: No such file or directory (os error 2)
  
29342/0x137ad:  open("/dev/dtracehelper\0", 0x2, 0xFFFFFFFFE75D1FB0)                                                                        = 3 0
29342/0x137ad:  open("/usr/share/terminfo/78/xterm-256color\0", 0x1000000, 0x1B6)                                                           = 3 0
29342/0x137ad:  open("/dev/urandom\0", 0x1000000, 0x1B6)                                                                                    = 4 0
29342/0x137ad:  open("/Users/AP/.rustup/settings.toml\0", 0x1000000, 0x1B6)                                                                 = 3 0
29342/0x137ad:  open("/synectic/GIT/syn6/BE_ApiGateway2/rust-toolchain\0", 0x1000000, 0x1B6)                                                = -1 Err#2
29342/0x137ad:  open("/synectic/GIT/syn6/rust-toolchain\0", 0x1000000, 0x1B6)                                                               = -1 Err#2
29342/0x137ad:  open("/synectic/GIT/rust-toolchain\0", 0x1000000, 0x1B6)                                                                    = -1 Err#2
29342/0x137ad:  open("/synectic/rust-toolchain\0", 0x1000000, 0x1B6)                                                                        = -1 Err#2
29342/0x137ad:  open("/rust-toolchain\0", 0x1000000, 0x1B6)                                                                                 = -1 Err#2
29342/0x137df:  open("/dev/dtracehelper\0", 0x2, 0xFFFFFFFFE4234E20)                                                                        = 3 0
29342/0x137df:  open("/dev/urandom\0", 0x1000000, 0x1B6)                                                                                    = 3 0
29342/0x137df:  open("/Users/AP/.gitconfig\0", 0x1000000, 0x0)                                                                              = 3 0
29342/0x137e0:  open("/dev/dtracehelper\0", 0x2, 0xFFFFFFFFE2651E10)                                                                        = 3 0
29342/0x137e0:  open("/dev/urandom\0", 0x1000000, 0x1B6)                                                                                    = 3 0
29342/0x137e0:  open("/synectic/GIT/syn6/BE_ApiGateway2/Cargo.toml\0", 0x1000000, 0x1B6)                                                    = 3 0
29342/0x137e0:  open("/synectic/GIT/syn6/BE_ApiGateway2/target/release/rpmbuild/SOURCES/BE_ApiGateway2-0.1.0.tar.gz\0", 0x1000601, 0x1B6)   = 3 0
29342/0x137e0:  open("/synectic/GIT/syn6/BE_ApiGateway2/target/release/BE_ApiGateway2\0", 0x1000000, 0x1B6)                                 = -1 Err#2
```

**Comment by avp90** [comment]
The directory / file `/synectic/GIT/syn6/BE_ApiGateway2/target/release/BE_ApiGateway2` doesn't exist. In the target dir are the following files (the `BE_ApiGateway2-0.1.0.tar.gz` is broken):  
<div align="center"><a href="https://imgbb.com/"><img width="300px" src="https://i.ibb.co/C5cPXvM/Bildschirmfoto-2019-08-28-um-09-13-15.png" alt="Bildschirmfoto-2019-08-28-um-09-13-15" border="0"></a></div>

**Comment by avp90** [comment]
I have solved the first problem with `cargo build --release` 😆 
Can you write this in your `README.md` please. In other build tools the rpm build plugins also builds the app for release, before build the rpm.

**Comment by avp90** [comment]
The next output is:  
```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/slice/mod.rs:2681:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
with backtrace:
```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/slice/mod.rs:2681:10
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: cargo_rpm::rpmbuild::Rpmbuild::version
   8: cargo_rpm::rpmbuild::Rpmbuild::new
   9: cargo_rpm::builder::Builder::build
  10: <cargo_rpm::commands::build::BuildCmd as abscissa_core::runnable::Runnable>::run
  11: abscissa_core::application::Application::run
  12: abscissa_core::application::boot
  13: cargo_rpm::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
  17: std::rt::lang_start_internal
  18: main
```

**Comment by avp90** [comment]
`rpmbuild --version` output:  
`RPM-Version 4.14.2.1`

**Comment by avp90** [comment]
same output on `centos-release-7-6.1810.2.el7.centos.x86_64`

**Comment by tarcieri** [comment]
>  In other build tools the rpm build plugins also builds the app for release, before build the rpm.

For some reason I thought it already did, but looking at the code, it does not!

I think the proper fix is for it to check if the release target exists, and if it doesn't, run the release build.

**Comment by avp90** [comment]
> I think the proper fix is for it to check if the release target exists, and if it doesn't, run the release build.

I think the safest is to build every time, like other plugins to use always the latest version.

**Comment by snocke** [comment]
Hi, 
does this problem still exists? We're getting the same results as described in this issue. 
`cargo rpm init` results in false `cargo.toml` and if we fix the `cargo.toml` manually the rpmbuild won't start and the error is the same as described here. We tried this with os x 10.15.7 and arch linux
`error: rpmbuild error: error running rpmbuild: No such file or directory (os error 2)`
